version: '3'

services:
  web:
    image: bee_ecommerce
    build: .
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db  # Conexões internas sempre usam o nome do serviço
      - DATABASE_PORT=3306 # Certifique-se de que a porta é interna
    entrypoint: ["sh", "-c", "/usr/local/bin/wait-for-it.sh db:3306 -- ./start.sh"]
    depends_on:
      - db
    networks:
      - bee_net

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    networks:
      - bee_net
    ports:
      - "3308:3306" # Externo:Interno, mas Django usará 3306 internamente

networks:
  bee_net:
    driver: bridge
